version: '3.8'

services:
  backend:
    build: ./backend
    container_name: novelistan-backend
    restart: always
    ports:
      - "8082:8082"
    environment:
      - PORT=8082
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=production
      - AZURE_STORAGE_ACCOUNT_NAME=${AZURE_STORAGE_ACCOUNT_NAME}
      - AZURE_STORAGE_ACCOUNT_KEY=${AZURE_STORAGE_ACCOUNT_KEY}
      - AZURE_STORAGE_CONTAINER_NAME=${AZURE_STORAGE_CONTAINER_NAME}
      - AZURE_STORAGE_SAS_TOKEN=${AZURE_STORAGE_SAS_TOKEN}
    volumes:
      - backend-uploads:/app/uploads

  frontend:
    build: ./novelistan
    container_name: novelistan-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=https://YOUR_RENDER_BACKEND_URL

volumes:
  backend-uploads:
